### ISSUE TITLE
$isCreditNote not available in template

### ISSUE THREAD

**Issue by aiden-grau** [mountev/uk.co.mountev.refundmanager#3]
$isCreditNote does not seem to be an available variable in the invoice template. I am using CiviCRM 5.50.1

**Comment by deepak-srivastava** [comment]
It's a custom var introduced through alterMailParams hook - https://github.com/mountev/uk.co.mountev.refundmanager/blob/master/refundmanager.php#L284.
You might wanna investigate and see if it's getting called/invoked.
